name: car_wash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  build_runner: ^2.4.7
  connectivity_plus: ^5.0.2
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.2
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/
    - assets/icons/
  uses-material-design: true
  fonts:
    - family: FontAwesome5ProRegular
      fonts:
        - asset: assets/fonts/Font Awesome 5 Pro Regular.otf
    - family: FontAwesome5ProLight
      fonts:
        - asset: assets/fonts/Font Awesome 5 Pro-Light-300.otf
          weight: 300
    - family: FontAwesome5ProRegular400
      fonts:
        - asset: assets/fonts/Font Awesome 5 Pro-Regular-400.otf
          weight: 400
    - family: FontAwesome5ProSolid
      fonts:
        - asset: assets/fonts/Font Awesome 5 Pro-Solid-900.otf
          weight: 900
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-SemiboldItalic.otf
          weight: 600
          style: italic
