// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3RHn1Y1rFMGX13zU3ZEb7dVgTvDCxrBM',
    appId: '1:809668854772:web:e1f016111b75bbc650afa1',
    messagingSenderId: '809668854772',
    projectId: 'car-wash-3a629',
    authDomain: 'car-wash-3a629.firebaseapp.com',
    storageBucket: 'car-wash-3a629.appspot.com',
    measurementId: 'G-HDTV8YLLYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfMAWkQARFBdEk42pX_K_JKDA2qn_EzA',
    appId: '1:809668854772:android:880f768b6e78362b50afa1',
    messagingSenderId: '809668854772',
    projectId: 'car-wash-3a629',
    storageBucket: 'car-wash-3a629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWwaKMehw76vUME_truRN138A7QMYEIvU',
    appId: '1:809668854772:ios:130474cf5efeb00650afa1',
    messagingSenderId: '809668854772',
    projectId: 'car-wash-3a629',
    storageBucket: 'car-wash-3a629.appspot.com',
    androidClientId: '809668854772-ekretmf9qhg7skli71vfbj1tit3b6hjl.apps.googleusercontent.com',
    iosClientId: '809668854772-ug0k3a7j3hi6ne1b73iaavcor7g4v20v.apps.googleusercontent.com',
    iosBundleId: 'com.example.carWash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWwaKMehw76vUME_truRN138A7QMYEIvU',
    appId: '1:809668854772:ios:4f73f0308003b53b50afa1',
    messagingSenderId: '809668854772',
    projectId: 'car-wash-3a629',
    storageBucket: 'car-wash-3a629.appspot.com',
    androidClientId: '809668854772-ekretmf9qhg7skli71vfbj1tit3b6hjl.apps.googleusercontent.com',
    iosClientId: '809668854772-nvn3cb52u80imsenboo5iuc792kbdi3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.carWash.RunnerTests',
  );
}
